services:
  # 1. Base de données PostgreSQL
  postgres:
    image: postgres:16
    container_name: ride-go-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: yowyob_db
      POSTGRES_USER: fleet_admin
      POSTGRES_PASSWORD: fleet_password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # 2. Cache Redis pour le tracking GPS
  redis:
    image: redis:alpine
    container_name: ride-go-redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass password

  # 3. Kafka (Redpanda) pour les notifications
  redpanda:
    image: docker.redpanda.com/redpandadata/redpanda:latest
    container_name: ride-go-kafka
    ports:
      - "9092:9092"
    command:
      - redpanda start
      - --overprovisioned
      - --smp 1
      - --memory 1G
      - --reserve-memory 0M
      - --node-id 0
      - --check=false
      - --kafka-addr plaintext://0.0.0.0:29092,external://0.0.0.0:9092
      - --advertise-kafka-addr plaintext://redpanda:29092,external://localhost:9092

  backend:
      image: ridngo-backend
      container_name: ride-go-api

      depends_on:
        - postgres
        - redis
        - redpanda

      ports:
        - "8080:8080"

      environment:

        SPRING_PROFILES_ACTIVE: prod

        DB_HOST: postgres
        DB_PORT: 5432
        DB_NAME: yowyob_db
        DB_SCHEMA: ride_and_go

        DB_USERNAME: fleet_admin
        DB_PASSWORD: fleet_password

        DB_LIQUIBASE_USERNAME: fleet_admin
        DB_LIQUIBASE_PASSWORD: fleet_password

        REDIS_HOST: redis
        REDIS_PORT: 6379
        REDIS_PASSWORD: password

        KAFKA_HOST: redpanda
        KAFKA_PORT: 29092

volumes:
  postgres_data: