package com.yowyob.rideandgo.infrastructure.adapters.inbound.rest.dto;

public record UpdateVehicleDto(
                String makeName,
                String modelName,
                String transmissionType,
                String manufacturerName,
                String sizeName,
                String typeName,
                String fuelTypeName,
                String vehicleSerialNumber,
                String registrationNumber,
                Double tankCapacity,
                Double luggageMaxCapacity,
                Integer totalSeatNumber,
                Double averageFuelConsumptionPerKm,
                Double mileageAtStart,
                Double mileageSinceCommissioning,
                Double vehicleAgeAtStart,
                Boolean airConditioned,
                Boolean comfortable,
                Boolean soft,
                Boolean screen,
                Boolean wifi,
                Boolean tollCharge,
                Boolean carParking,
                Boolean alarm,
                Boolean stateTax,
                Boolean driverAllowance,
                Boolean pickupAndDrop,
                Boolean internet,
                Boolean petsAllow) {
}